version: '3.1'

services:
  demo:
    image: formapro/nginx-php-fpm:latest-all-exts
    depends_on:
      - mongo
    volumes:
      - './:/app'
    environment:
      - ENQUEUE_DSN=file://app/var/queue
      - MONGO_DSN=mongodb://mongo/pvm_demo
      - NGINX_WEB_ROOT=/app/public
    ports:
      - '80:80'

  mongo:
      image: 'mongo:3.7'
      ports:
        - '27017:27017'
