version: '3.1'

services:
  demo:
    image: 'formapro/pvm-demo:latest'
    depends_on:
      - mongo
      - rabbitmq
    env_file:
      - '.env'
    ports:
      - '80:80'

  mongo:
      image: 'mongo:3.7'
      ports:
        - '27017:27017'

  rabbitmq:
    image: 'rabbitmq:management'
    restart: 'always'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=pvm_demo
    ports:
      - '15672:15672'
